import test from 'node:test';
import assert from 'node:assert/strict';
import { adaptiveGridDisplay, readVerifiedSnapshot, saveVerifiedSnapshot, snapshotIsSafe } from '../assets/dashboard-resilience.js';

const TRIAL_ID = 'btc-shadow-90d-20260817T173948Z';
function storage(){const values=new Map();return{getItem:k=>values.has(k)?values.get(k):null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k)}}
function fixture(status='VERIFIED') {return {apiVersion:'btc-shadow-dashboard-readonly/2.1',generatedAt:'2026-09-06T06:00:00.000Z',mode:'SHADOW',spotOnly:true,automaticExecution:false,firebaseToken:'must-not-persist',account:{email:'must-not-persist@example.invalid'},runtime:{shadowMode:true,operationMode:'SPOT_ONLY',allowShort:false,ready:true},trial:{trialId:TRIAL_ID,status,completedDays:16,requiredDays:90},decisions:Array.from({length:30},(_,i)=>({horizon:'5m',reason:`r${i}`})),paper:{status:'WAITING_CONDITIONS',recentRuns:[{runId:'must-not-persist'}],funnel:{counts:{observed:5,eligible:0}},paper:{activeOpen:0,verified:0,metrics:{verifiedTrades:0},trades:[]}},adaptiveGrid:{protocol:'btc-adaptive-grid-dashboard-evidence/1.0',generatedAt:'2026-09-06T06:00:00.000Z',status:'COLLECTING',targetDecisions:100,totalDecisions:1,remainingDecisions:99,progressPct:1,modes:{gridActive:1,gridDefensive:0,abstain:0},maturedOutcomes:0,completedCycles:0,netPnl:0,firstReviewReady:false,evidenceBasis:'VERIFIED_APPEND_ONLY_PROSPECTIVE_CHAIN',safety:{shadowMode:true,spotOnly:true,readOnly:true,sendToExchange:false,realOrderCreated:false,formalTrialMutation:false,countsTowardFormal90D:false,productionEligible:false}}}}

test('live payload safety is independent from formal trial verification status',()=>{assert.equal(snapshotIsSafe(fixture('VERIFIED'),TRIAL_ID),true);assert.equal(snapshotIsSafe(fixture('INITIALIZED'),TRIAL_ID),true);assert.equal(snapshotIsSafe(fixture('BLOCKED'),TRIAL_ID),true)});
test('unsafe runtime and wrong trial fail closed',()=>{const unsafe=fixture();unsafe.runtime.allowShort=true;assert.equal(snapshotIsSafe(unsafe,TRIAL_ID),false);assert.equal(snapshotIsSafe(fixture(),'wrong-trial'),false)});
test('X/100 appears only from verified prospective chain and never fabricates zero',()=>{assert.deepEqual(adaptiveGridDisplay(fixture().adaptiveGrid),{counter:'1 / 100',state:'VERIFICADO',valid:true});const zero=fixture().adaptiveGrid;zero.totalDecisions=0;assert.equal(adaptiveGridDisplay(zero).counter,'-- / 100');const bad=fixture().adaptiveGrid;bad.evidenceBasis='STATIC_READINESS';assert.equal(adaptiveGridDisplay(bad).valid,false);assert.equal(adaptiveGridDisplay(bad).counter,'-- / 100')});
test('cache persists bounded projection and prospective Adaptive Grid evidence',()=>{const s=storage();assert.equal(saveVerifiedSnapshot(s,'k',fixture(),TRIAL_ID,90,1000),true);const raw=s.getItem('k');assert.ok(raw);assert.equal(raw.includes('must-not-persist'),false);assert.equal(raw.includes('recentRuns'),false);const cached=JSON.parse(raw);assert.equal(cached.data.decisions.length,15);assert.equal(cached.data.paper.funnel.counts.observed,5);assert.equal(cached.data.adaptiveGrid.totalDecisions,1);assert.equal(cached.data.adaptiveGrid.targetDecisions,100);assert.equal(cached.data.adaptiveGrid.evidenceBasis,'VERIFIED_APPEND_ONLY_PROSPECTIVE_CHAIN');assert.equal(cached.data.adaptiveGrid.safety.countsTowardFormal90D,false)});
test('non-verified snapshots are never written',()=>{const s=storage();assert.equal(saveVerifiedSnapshot(s,'k',fixture('INITIALIZED'),TRIAL_ID,90,1000),false);assert.equal(s.getItem('k'),null)});
test('expired, future-dated, corrupt, or unsafe cache is rejected and removed',()=>{const now=2_000_000_000,cases=[JSON.stringify({savedAt:now-(24*60*60*1000)-1,data:fixture()}),JSON.stringify({savedAt:now+60_001,data:fixture()}),'{bad json',JSON.stringify({savedAt:now-1000,data:fixture('BLOCKED')})];for(const value of cases){const s=storage();s.setItem('k',value);assert.equal(readVerifiedSnapshot(s,'k',TRIAL_ID,90,now),null);assert.equal(s.getItem('k'),null)}});
test('fresh VERIFIED cache remains readable',()=>{const now=2_000_000_000,s=storage();s.setItem('k',JSON.stringify({savedAt:now-1000,data:fixture()}));const cached=readVerifiedSnapshot(s,'k',TRIAL_ID,90,now);assert.equal(cached?.trial.completedDays,16);assert.equal(cached?.adaptiveGrid.totalDecisions,1)});
