import test from 'node:test';
import assert from 'node:assert/strict';
import { rawEconomicDisplay } from '../assets/raw-economic-resilience.js';
import { saveVerifiedSnapshot, readVerifiedSnapshot } from '../assets/dashboard-resilience.js';

const TRIAL_ID='btc-shadow-90d-20260817T173948Z';
const safe={shadowMode:true,spotOnly:true,readOnly:true,sendToExchange:false,exchangeCredentials:false,realOrdersAllowed:false,formalTrialMutation:false,countsTowardFormal90D:false,countsTowardCurrentV2:false,automaticPromotion:false,canAuthorizeTrading:false};
function raw(){return{protocol:'btc-adaptive-grid-v2-raw-economic-progress/1.0',status:'COLLECTING',targetMaturedActivatedOutcomes:20,targetBuyFills:20,targetTpSellCycles:10,maturedActivatedOutcomes:8,buyFills:12,tpSellCycles:6,residualInventoryOutcomes:2,totalNetPnlAfterCosts:1.23456,chainValid:true,exactSourceOutcomeReconciliation:true,provenanceViolations:0,auditErrors:0,rawSufficiencyReady:false,activation:{activationId:'raw-beta-da4ba8a994edd86deec80741',baselineDecisionSequence:186,sourceCommit:'03532e23d4afcdf6ca2a4581a9adc3e1a834572d'},source:{authoritative:true,generation:'123'},countsTowardCurrentV2:false,countsTowardFormal90D:false,canAuthorizeTrading:false,liveTradingEligible:false,safety:{...safe}}}
function payload(){return{apiVersion:'btc-shadow-dashboard-readonly/2.2',generatedAt:'2026-09-09T21:00:00.000Z',mode:'SHADOW',spotOnly:true,automaticExecution:false,runtime:{shadowMode:true,operationMode:'SPOT_ONLY',allowShort:false},trial:{trialId:TRIAL_ID,status:'VERIFIED',completedDays:16,requiredDays:90},rawEconomic:raw(),secretField:'must-not-persist'}}
function storage(){const x=new Map();return{getItem:k=>x.has(k)?x.get(k):null,setItem:(k,v)=>x.set(k,String(v)),removeItem:k=>x.delete(k)}}

test('renders authoritative raw beta counters without implying trading authority',()=>{const v=rawEconomicDisplay(raw());assert.equal(v.outcomes,'8 / 20');assert.equal(v.buys,'12 / 20');assert.equal(v.tp,'6 / 10');assert.equal(v.pnl,'1.2346 USDT');assert.equal(v.authority,'NO AUTORIZA TRADING');assert.equal(v.valid,true)});
test('fails closed on source, authority or audit drift',()=>{for(const mutate of [r=>r.source.authoritative=false,r=>r.canAuthorizeTrading=true,r=>r.safety.sendToExchange=true,r=>r.maturedActivatedOutcomes=null,r=>r.targetTpSellCycles=9,r=>r.chainValid=false,r=>r.exactSourceOutcomeReconciliation=false,r=>r.provenanceViolations=1,r=>r.auditErrors=1]){const r=raw();mutate(r);const v=rawEconomicDisplay(r);assert.equal(v.valid,false);assert.equal(v.outcomes,'-- / 20');assert.equal(v.authority,'NO AUTORIZA TRADING')}});
test('sufficient raw evidence still cannot authorize trading',()=>{const r=raw();Object.assign(r,{status:'SUFFICIENT_FOR_INDEPENDENT_REVIEW',maturedActivatedOutcomes:20,buyFills:25,tpSellCycles:12,rawSufficiencyReady:true});const v=rawEconomicDisplay(r);assert.equal(v.valid,true);assert.equal(v.authority,'NO AUTORIZA TRADING')});
test('verified local cache deliberately excludes raw beta evidence',()=>{const s=storage(),p=payload();assert.equal(saveVerifiedSnapshot(s,'k',p,TRIAL_ID,90,1000),true);const text=s.getItem('k');assert.equal(text.includes('rawEconomic'),false);assert.equal(text.includes('raw-beta-da4ba8a994edd86deec80741'),false);const cached=readVerifiedSnapshot(s,'k',TRIAL_ID,90,1001);assert.equal(cached.rawEconomic,undefined)});
